export interface CustomerOption {
  warehouseCode: string;
  customerCode: string;
  customerName: string;
}

export interface WarehouseProfileSummary {
  id: number;
  companyCode: string;
  warehouseCode: string;
  customerCode: string;
  profileName: string;
  description: string | null;
  warehouseLength: number | null;
  warehouseWidth: number | null;
  createdAt: string | null;
  updatedAt: string | null;
  sharedProfile: boolean;
}

export interface WarehouseLayoutLocation {
  location: string;
  zone: string | null;
  type: string | null;
  level: number | null;
  aisle: number | null;
  position: number | null;
  side: string | null;
  x: number | null;
  y: number | null;
  footprintWidth?: number | null;
  footprintDepth?: number | null;
  slottedClass?: string | null;
  slottedSku?: string | null;
}

export interface WarehouseBoundaryPoint {
  x: number;
  y: number;
}

export interface WarehouseAisle {
  id: number;
  x: number;
  y: number;
  width: number;
  height: number;
  type: string;
  direction?: string | null;
  workingStatusFlow?: string | null;
  workingStatusCode?: string | null;
  workingStatusLabel?: string | null;
  workingStatusColor?: string | null;
  levels: number;
  zone: string;
  aisleCode?: string | null;
  bayWidth: number;
  bayDepth: number;
  aisleWidth: number;
  tunnelLevelFrom?: number | null;
  tunnelLevelTo?: number | null;
  lowerShelfLevels?: number | null;
  pickFaceLevels?: number[] | null;
  startPointX?: number | null;
  startPointY?: number | null;
  baseLocations?: WarehouseLayoutLocation[] | null;
  locations: WarehouseLayoutLocation[];
}

export interface WarehouseLayout {
  warehouseWidth: number;
  warehouseHeight: number;
  boundaryPolygon?: WarehouseBoundaryPoint[] | null;
  aisles: WarehouseAisle[];
}

export type WarehouseDesignerLayout = WarehouseLayout;

export interface WarehouseProfileDetail extends WarehouseProfileSummary {
  layoutData: string;
  locations: WarehouseLayoutLocation[];
}

export interface WarehouseDesignDraft {
  profileId: number | null;
  profileName: string;
  description: string;
  warehouseWidth: number;
  warehouseHeight: number;
  layout: WarehouseDesignerLayout;
}

export interface AutoGeneratedLayoutSummary {
  areas: number;
  racks: number;
  locations: number;
  inferredPositions: number;
  inferredLevels: number;
  skippedRows: number;
  warehouseWidth?: number | null;
  warehouseHeight?: number | null;
  normalizedDimensionRows?: number;
  normalizedHeightRows?: number;
  rotatedAreas?: number;
  mixedAreasDetected?: number;
  mixedAreasUncertain?: number;
}

export interface AutoGeneratedLayoutResponse {
  layout: WarehouseLayout;
  summary: AutoGeneratedLayoutSummary;
  warnings: string[];
}

export type WarehouseLocationHierarchyScope = 'WAREHOUSE' | 'WAREHOUSE_CUSTOMER';
export type WarehouseLocationHierarchySource = 'AREA_CODE' | 'RACK_CODE' | 'POSITION_CODE' | 'LEVEL_CODE';

export interface WarehouseLocationHierarchyMapping {
  zone?: WarehouseLocationHierarchySource | null;
  aisle?: WarehouseLocationHierarchySource | null;
  bay: WarehouseLocationHierarchySource;
  slot?: WarehouseLocationHierarchySource | null;
  level: WarehouseLocationHierarchySource;
}

export interface WarehouseLocationHierarchySetting {
  id: number;
  scope: WarehouseLocationHierarchyScope;
  companyCode: string;
  warehouseCode: string;
  customerCode: string | null;
  mapping: WarehouseLocationHierarchyMapping;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface WarehouseLocationHierarchyResponse {
  warehouseDefault: WarehouseLocationHierarchySetting | null;
  customerOverride: WarehouseLocationHierarchySetting | null;
  effective: WarehouseLocationHierarchySetting | null;
}

export interface ProductRecord {
  id?: number;
  sku: string;
  name: string;
  category: string | null;
  weight: number | null;
  volume: number | null;
  width: number | null;
  height: number | null;
  depth: number | null;
  demandFrequency: number | null;
  velocityClass: string | null;
  variabilityClass: string | null;
  uom: string | null;
  picksPerDay: number | null;
  avgQtyPerPick: number | null;
}

export interface SlottingAssignment {
  id?: number;
  profileId: number;
  customerCode: string;
  location: string;
  zone: string | null;
  productSku: string;
  productName: string;
  productCategory: string | null;
  velocityClass: string | null;
  demandFrequency: number | null;
  assignmentScore: number | null;
  assignmentReason: string | null;
  assignedAt?: string | null;
}

export interface OrderLine {
  id?: number;
  sku: string;
  productName: string;
  location: string;
  quantity: number;
  pickSequence: number | null;
  originalSequence: number | null;
}

export interface PickOrder {
  id: number;
  profileId: number;
  customerCode: string;
  orderNumber: string;
  priority: number;
  status: string;
  linesCount: number;
  totalQuantity: number;
  createdAt: string | null;
  optimizedAt: string | null;
  lines: OrderLine[];
}

export interface RouteNode {
  name: string;
  sku?: string | null;
  x: number | null;
  y: number | null;
  level: number | null;
}

export interface RouteResult {
  method: string;
  route: string[];
  distance: number;
  percent: number | null;
}

export interface RouteOptimizationResult {
  orderId: number;
  startPoint: RouteNode;
  original: RouteResult;
  optimized: RouteResult[];
  best: RouteResult;
  comparison: RouteResult[];
}

export interface VelocityDistribution {
  velocityClass: string;
  count: number;
  avgScore: number | null;
}

export interface ZoneDistribution {
  zone: string;
  count: number;
}

export interface AlgorithmComparison {
  algorithm: string;
  orderCount: number;
  avgOriginalDistance: number | null;
  avgOptimizedDistance: number | null;
  avgImprovement: number | null;
}

export interface BestAlgorithmUse {
  algorithm: string;
  timesBest: number;
}

export interface SlottingAnalytics {
  velocityDistribution: VelocityDistribution[];
  zoneDistribution: ZoneDistribution[];
}

export interface PickingAnalytics {
  algorithmComparison: AlgorithmComparison[];
  bestAlgorithmUsage: BestAlgorithmUse[];
  totalOrders: number;
  optimizedOrders: number;
}

export interface WarehouseOptimizeAnalytics {
  slotting: SlottingAnalytics;
  picking: PickingAnalytics;
}

export interface ViewerDiagnostics {
  unmatchedLayoutLocations: string[];
  unmatchedStockLocations: string[];
}

export interface LiveLocationState {
  location: string;
  zone: string | null;
  type: string | null;
  level: number | null;
  x: number | null;
  y: number | null;
  customerCode: string;
  productCode: string | null;
  productCategory: string | null;
  velocityClass: string | null;
  colorClass: string;
  physicalQty: number | null;
  availableQty: number | null;
  blink: boolean;
  updatedAt: string | null;
}

export interface StockSyncSnapshot {
  profileId: number;
  customerCode: string;
  syncedAt: string;
  cursor: string;
  locations: LiveLocationState[];
  diagnostics: ViewerDiagnostics;
}

export interface StockDelta {
  profileId: number;
  customerCode: string;
  previousCursor: string | null;
  cursor: string;
  changedLocations: LiveLocationState[];
  diagnostics: ViewerDiagnostics;
}

export interface WorkingStatusSnapshotItem {
  flow: string;
  statusCode: string;
  statusLabel: string;
  color: string;
  orderCount: number;
  totalOrders: number;
  csQty: number | null;
  pcsQty: number | null;
}

export interface WorkingStatusSnapshotResponse {
  generatedAt: string | null;
  statuses: WorkingStatusSnapshotItem[];
}

export interface WorkingStatusZoneSnapshot {
  aisleId: number;
  zone: string;
  flow: string;
  statusCode: string;
  statusLabel: string;
  color: string;
  orderCount: number;
  totalOrders: number;
  csQty: number;
  pcsQty: number;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ProductsSummaryResponse {
  success: boolean;
  count: number;
  summary?: Record<string, number>;
}

export interface SlottingAssignmentsResponse {
  assignments: SlottingAssignment[];
  count: number;
  summary: Record<string, number>;
}

export interface OrdersMutationResponse {
  success: boolean;
  ordersCreated: number;
  linesCreated: number;
}

export type ZoneNamingPattern = 'prefix-row' | 'prefixrow' | 'prefix-row-suffix' | 'custom';
export type LocationNamingPattern = 'zone-row-bay-level' | 'zone-bay-level' | 'zone-row-bay-side-level' | 'custom';
export type GeneratorRowFormat = 'numeric' | 'alpha' | 'alpha2';
export type BayNumberingPattern = 'running' | 'odd' | 'even';

export interface LayoutGeneratorConfig {
  warehouseWidth: number;
  warehouseHeight: number;
  aisleCount: number;
  baysPerAisle: number;
  levels: number;
  zonePrefix: string;
  zoneStartNumber: number;
  zoneNamingPattern: ZoneNamingPattern;
  zoneSuffix: string;
  customZonePattern: string;
  locationNamingPattern: LocationNamingPattern;
  customLocationPattern: string;
  rowFormat: GeneratorRowFormat;
  rowPadding: number;
  bayPadding: number;
  levelPrefix: string;
  leftBayNumbering: BayNumberingPattern;
  rightBayNumbering: BayNumberingPattern;
  rowNumberStart: number;
  bayNumberStart: number;
  levelNumberStart: number;
  rackType: string;
  bayWidth: number;
  bayDepth: number;
  aisleWidth: number;
  startX: number;
  startY: number;
}

export interface LayoutStats {
  aisles: number;
  locations: number;
  highRack: number;
  shelf: number;
  driveIn: number;
  floor: number;
}
