package jp.co.nittsu.gwh.module.warehouseoptimize.controller;

import jp.co.nittsu.gwh.module.warehouseoptimize.dto.WarehouseOptimizeModels;
import jp.co.nittsu.gwh.module.warehouseoptimize.service.WarehouseOptimizeService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.math.BigDecimal;
import java.util.Collections;

import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ExtendWith(MockitoExtension.class)
class WarehouseOptimizeControllerTest {

    @Mock
    private WarehouseOptimizeService service;

    @InjectMocks
    private WarehouseOptimizeController controller;

    @Test
    void autoGenerateLayoutReturnsSuccessEnvelope() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.standaloneSetup(controller).build();

        WarehouseOptimizeModels.WarehouseLayout layout = new WarehouseOptimizeModels.WarehouseLayout();
        layout.setWarehouseWidth(new BigDecimal("32.4"));
        layout.setWarehouseHeight(new BigDecimal("18.0"));
        layout.setBoundaryPolygon(null);
        layout.setAisles(Collections.emptyList());

        WarehouseOptimizeModels.AutoGeneratedLayoutSummary summary = new WarehouseOptimizeModels.AutoGeneratedLayoutSummary();
        summary.setAreas(2);
        summary.setRacks(4);
        summary.setLocations(48);
        summary.setInferredPositions(3);
        summary.setInferredLevels(2);
        summary.setSkippedRows(1);

        WarehouseOptimizeModels.AutoGeneratedLayoutResponse response = new WarehouseOptimizeModels.AutoGeneratedLayoutResponse();
        response.setLayout(layout);
        response.setSummary(summary);
        response.setWarnings(Collections.singletonList("Skipped duplicate canonical location A01R1011."));

        when(service.autoGenerateLayout()).thenReturn(response);

        mockMvc.perform(post("/api/v1/warehouse-optimize/layout/auto-generate")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.status").value("SUCCESS"))
            .andExpect(jsonPath("$.data.layout.warehouseWidth").value(32.4))
            .andExpect(jsonPath("$.data.summary.areas").value(2))
            .andExpect(jsonPath("$.data.summary.skippedRows").value(1))
            .andExpect(jsonPath("$.data.warnings[0]").value("Skipped duplicate canonical location A01R1011."));
    }

    @Test
    void workingStatusSnapshotReturnsSuccessEnvelope() throws Exception {
        MockMvc mockMvc = MockMvcBuilders.standaloneSetup(controller).build();

        WarehouseOptimizeModels.WorkingStatusSnapshotItem item = new WarehouseOptimizeModels.WorkingStatusSnapshotItem();
        item.setFlow("OUTBOUND");
        item.setStatusCode("500");
        item.setStatusLabel("Picking");
        item.setColor("#FF9E1B");
        item.setOrderCount(7);
        item.setTotalOrders(25);
        item.setCsQty(new BigDecimal("11"));
        item.setPcsQty(new BigDecimal("90"));

        WarehouseOptimizeModels.WorkingStatusSnapshotResponse response = new WarehouseOptimizeModels.WorkingStatusSnapshotResponse();
        response.setStatuses(Collections.singletonList(item));

        when(service.loadWorkingStatusSnapshot("TESA")).thenReturn(response);

        mockMvc.perform(post("/api/v1/warehouse-optimize/viewer/working-status")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"customerCode\":\"TESA\"}"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.status").value("SUCCESS"))
            .andExpect(jsonPath("$.data.statuses[0].flow").value("OUTBOUND"))
            .andExpect(jsonPath("$.data.statuses[0].statusCode").value("500"))
            .andExpect(jsonPath("$.data.statuses[0].orderCount").value(7))
            .andExpect(jsonPath("$.data.statuses[0].totalOrders").value(25))
            .andExpect(jsonPath("$.data.statuses[0].csQty").value(11))
            .andExpect(jsonPath("$.data.statuses[0].pcsQty").value(90));
    }
}
