import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { ButtonModule } from 'primeng/button';
import { DropdownModule } from 'primeng/dropdown';
import { CalendarModule } from 'primeng/calendar';
import { TabViewModule } from 'primeng/tabview';
import { TagModule } from 'primeng/tag';
import { TableModule } from 'primeng/table';
import { PageHeaderComponent } from '@shared/components/page-header/page-header.component';

@Component({
  selector: 'wms-reports',
  standalone: true,
  imports: [CommonModule, FormsModule, TranslateModule, ButtonModule, DropdownModule,
            CalendarModule, TabViewModule, TagModule, TableModule, PageHeaderComponent],
  template: `
    <wms-page-header title="reports.title" subtitle="reports.subtitle" icon="pi pi-chart-bar">
    </wms-page-header>

    <p-tabView>
      <!-- Report Catalog -->
      <p-tabPanel header="Report Catalog" leftIcon="pi pi-list">
        <div class="reports-grid">
          @for (cat of reportCategories; track cat.name) {
            <div class="category-section">
              <h3 class="category-title">
                <i [class]="cat.icon" [style.color]="cat.color"></i>
                {{ cat.name }}
              </h3>
              <div class="report-cards">
                @for (r of cat.reports; track r.id) {
                  <div class="report-card" (click)="selectReport(r)">
                    <div class="report-icon" [style.background]="cat.bgColor">
                      <i [class]="r.icon" [style.color]="cat.color"></i>
                    </div>
                    <div class="report-info">
                      <span class="report-name">{{ r.name }}</span>
                      <span class="report-desc">{{ r.description }}</span>
                    </div>
                    <div class="report-formats">
                      @for (fmt of r.formats; track fmt) {
                        <span class="format-badge" [class]="'fmt-' + fmt.toLowerCase()">{{ fmt }}</span>
                      }
                    </div>
                  </div>
                }
              </div>
            </div>
          }
        </div>
      </p-tabPanel>

      <!-- Generate Report -->
      <p-tabPanel header="Generate Report" leftIcon="pi pi-file-export">
        <div class="generate-layout">
          <div class="wms-card">
            <h3 class="section-title">Report Parameters</h3>
            <div class="param-grid">
              <div class="param-field">
                <label>Report</label>
                <p-dropdown [options]="allReports" [(ngModel)]="selectedReportId" placeholder="Select report..." styleClass="w-full"></p-dropdown>
              </div>
              <div class="param-field">
                <label>Format</label>
                <p-dropdown [options]="formats" [(ngModel)]="selectedFormat" styleClass="w-full"></p-dropdown>
              </div>
              <div class="param-field">
                <label>Date From</label>
                <p-calendar [(ngModel)]="dateFrom" dateFormat="yy-mm-dd" [showIcon]="true" styleClass="w-full"></p-calendar>
              </div>
              <div class="param-field">
                <label>Date To</label>
                <p-calendar [(ngModel)]="dateTo" dateFormat="yy-mm-dd" [showIcon]="true" styleClass="w-full"></p-calendar>
              </div>
              <div class="param-field">
                <label>Warehouse</label>
                <p-dropdown [options]="warehouses" [(ngModel)]="selectedWarehouse" placeholder="All" [showClear]="true" styleClass="w-full"></p-dropdown>
              </div>
            </div>
            <div class="generate-actions">
              <button pButton label="Preview" icon="pi pi-eye" class="p-button-outlined p-button-sm" (click)="previewReport()"></button>
              <button pButton label="Generate & Download" icon="pi pi-download" class="p-button-sm" (click)="generateReport()"
                      [disabled]="!selectedReportId || !selectedFormat"></button>
            </div>
          </div>
        </div>
      </p-tabPanel>

      <!-- Report History -->
      <p-tabPanel header="History" leftIcon="pi pi-history">
        <div class="wms-card">
          <p-table [value]="reportHistory" [paginator]="true" [rows]="10" styleClass="p-datatable-sm p-datatable-gridlines">
            <ng-template pTemplate="header">
              <tr>
                <th style="width:160px">Date</th>
                <th>Report Name</th>
                <th style="width:80px">Format</th>
                <th style="width:100px">Status</th>
                <th style="width:120px">Generated By</th>
                <th style="width:80px">Size</th>
                <th style="width:80px"></th>
              </tr>
            </ng-template>
            <ng-template pTemplate="body" let-h>
              <tr>
                <td>{{ h.date }}</td>
                <td class="font-semibold">{{ h.name }}</td>
                <td><span class="format-badge" [class]="'fmt-' + h.format.toLowerCase()">{{ h.format }}</span></td>
                <td><p-tag [value]="h.status" [severity]="h.status === 'Ready' ? 'success' : h.status === 'Processing' ? 'info' : 'danger'" [rounded]="true"></p-tag></td>
                <td>{{ h.user }}</td>
                <td>{{ h.size }}</td>
                <td>
                  <button pButton icon="pi pi-download" class="p-button-text p-button-sm p-button-rounded"
                          [disabled]="h.status !== 'Ready'" (click)="downloadReport(h)"></button>
                </td>
              </tr>
            </ng-template>
          </p-table>
        </div>
      </p-tabPanel>

      <!-- Scheduled Reports -->
      <p-tabPanel header="Scheduled" leftIcon="pi pi-clock">
        <div class="wms-card">
          <div class="schedule-header">
            <h3 class="section-title" style="margin:0">Scheduled Reports</h3>
            <button pButton label="New Schedule" icon="pi pi-plus" class="p-button-sm p-button-outlined"></button>
          </div>
          <div class="schedule-list">
            @for (s of scheduledReports; track s.id) {
              <div class="schedule-item">
                <div class="schedule-icon" [style.background]="s.active ? '#ecfccb' : '#f3f4f6'">
                  <i class="pi pi-clock" [style.color]="s.active ? '#8EC400' : '#9ca3af'"></i>
                </div>
                <div class="schedule-info">
                  <span class="schedule-name">{{ s.name }}</span>
                  <span class="schedule-cron">{{ s.schedule }}</span>
                </div>
                <div class="schedule-meta">
                  <span class="schedule-next">Next: {{ s.nextRun }}</span>
                  <span class="schedule-format format-badge" [class]="'fmt-' + s.format.toLowerCase()">{{ s.format }}</span>
                </div>
                <p-tag [value]="s.active ? 'Active' : 'Paused'" [severity]="s.active ? 'success' : 'warning'" [rounded]="true"></p-tag>
              </div>
            }
          </div>
        </div>
      </p-tabPanel>
    </p-tabView>
  `,
  styles: [`
    .wms-card { background: white; border-radius: 14px; border: 1px solid #e5e7eb; padding: 20px; }
    .section-title { font-size: 15px; font-weight: 700; color: #111827; margin: 0 0 16px; }
    .reports-grid { display: flex; flex-direction: column; gap: 24px; }
    .category-title { font-size: 16px; font-weight: 700; color: #111827; display: flex; align-items: center; gap: 8px; margin: 0 0 12px; }
    .report-cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 12px; }
    .report-card { background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; display: flex; align-items: center; gap: 14px;
                   cursor: pointer; transition: all .15s; }
    .report-card:hover { border-color: #c7d2fe; background: #fafbff; box-shadow: 0 2px 8px rgba(0,0,0,.04); }
    .report-icon { width: 42px; height: 42px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 18px; flex-shrink: 0; }
    .report-info { flex: 1; display: flex; flex-direction: column; gap: 2px; }
    .report-name { font-weight: 600; font-size: 14px; color: #111827; }
    .report-desc { font-size: 12px; color: #6b7280; }
    .report-formats { display: flex; gap: 4px; }
    .format-badge { font-size: 10px; font-weight: 700; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; }
    .fmt-pdf { background: #fef2f2; color: #ef4444; }
    .fmt-excel { background: #ecfccb; color: #65a30d; }
    .fmt-csv { background: #e0f2fe; color: #0284c7; }
    .param-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 14px; }
    .param-field { display: flex; flex-direction: column; gap: 4px; }
    .param-field label { font-size: 12px; font-weight: 600; color: #374151; }
    .w-full { width: 100%; }
    .generate-actions { display: flex; gap: 10px; justify-content: flex-end; margin-top: 16px; }
    .font-semibold { font-weight: 600; }
    .schedule-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; }
    .schedule-list { display: flex; flex-direction: column; gap: 10px; }
    .schedule-item { display: flex; align-items: center; gap: 14px; padding: 14px 16px; border: 1px solid #e5e7eb; border-radius: 10px; }
    .schedule-icon { width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; }
    .schedule-info { flex: 1; display: flex; flex-direction: column; gap: 2px; }
    .schedule-name { font-weight: 600; font-size: 14px; color: #111827; }
    .schedule-cron { font-size: 12px; color: #6b7280; font-family: monospace; }
    .schedule-meta { display: flex; flex-direction: column; align-items: flex-end; gap: 4px; }
    .schedule-next { font-size: 12px; color: #6b7280; }
  `]
})
export class ReportsComponent {
  selectedReportId: string | null = null;
  selectedFormat: string | null = null;
  dateFrom: Date | null = null;
  dateTo: Date | null = null;
  selectedWarehouse: string | null = null;

  formats = [
    { label: 'PDF', value: 'PDF' }, { label: 'Excel', value: 'Excel' }, { label: 'CSV', value: 'CSV' }
  ];
  warehouses = [
    { label: 'WH-TKY01', value: 'WH-TKY01' }, { label: 'WH-OSK01', value: 'WH-OSK01' },
    { label: 'WH-NGY01', value: 'WH-NGY01' }
  ];

  reportCategories = [
    {
      name: 'Inbound Reports', icon: 'pi pi-sign-in', color: '#8EC400', bgColor: '#ecfccb',
      reports: [
        { id: 'inb-summary', name: 'Inbound Summary', description: 'Daily/weekly arrival order summary', icon: 'pi pi-chart-bar', formats: ['PDF', 'Excel'] },
        { id: 'inb-detail', name: 'Receiving Detail', description: 'Item-level receiving records', icon: 'pi pi-list', formats: ['Excel', 'CSV'] },
        { id: 'inb-variance', name: 'Receiving Variance', description: 'Expected vs actual qty differences', icon: 'pi pi-exclamation-triangle', formats: ['PDF', 'Excel'] },
      ]
    },
    {
      name: 'Outbound Reports', icon: 'pi pi-sign-out', color: '#5BC2E7', bgColor: '#e0f2fe',
      reports: [
        { id: 'out-summary', name: 'Shipment Summary', description: 'Daily/weekly shipment order summary', icon: 'pi pi-chart-bar', formats: ['PDF', 'Excel'] },
        { id: 'out-picking', name: 'Picking Accuracy', description: 'Pick accuracy rate analysis', icon: 'pi pi-check-circle', formats: ['PDF'] },
        { id: 'out-carrier', name: 'Carrier Performance', description: 'On-time delivery by carrier', icon: 'pi pi-truck', formats: ['PDF', 'Excel'] },
      ]
    },
    {
      name: 'Inventory Reports', icon: 'pi pi-database', color: '#1A005D', bgColor: '#ede9fe',
      reports: [
        { id: 'inv-snapshot', name: 'Inventory Snapshot', description: 'Current stock levels for all products', icon: 'pi pi-camera', formats: ['Excel', 'CSV'] },
        { id: 'inv-movement', name: 'Stock Movement', description: 'All stock in/out transactions', icon: 'pi pi-arrows-h', formats: ['Excel', 'CSV'] },
        { id: 'inv-aging', name: 'Inventory Aging', description: 'Stock age by lot/expiry date', icon: 'pi pi-clock', formats: ['PDF', 'Excel'] },
        { id: 'inv-valuation', name: 'Inventory Valuation', description: 'Stock value by product/location', icon: 'pi pi-dollar', formats: ['PDF', 'Excel'] },
      ]
    },
    {
      name: 'Operational Reports', icon: 'pi pi-cog', color: '#FF9E1B', bgColor: '#fff7ed',
      reports: [
        { id: 'ops-productivity', name: 'Operator Productivity', description: 'Tasks per operator per shift', icon: 'pi pi-users', formats: ['PDF', 'Excel'] },
        { id: 'ops-utilization', name: 'Warehouse Utilization', description: 'Space utilization over time', icon: 'pi pi-building', formats: ['PDF'] },
      ]
    }
  ];

  get allReports(): any[] {
    const reports: any[] = [];
    this.reportCategories.forEach(cat => cat.reports.forEach(r => reports.push({ label: r.name, value: r.id })));
    return reports;
  }

  reportHistory = [
    { date: '2024-06-15 14:30', name: 'Inventory Snapshot', format: 'Excel', status: 'Ready', user: 'T. Tanaka', size: '2.4 MB' },
    { date: '2024-06-15 12:15', name: 'Shipment Summary', format: 'PDF', status: 'Ready', user: 'S. Suzuki', size: '1.1 MB' },
    { date: '2024-06-15 10:00', name: 'Stock Movement', format: 'CSV', status: 'Ready', user: 'admin', size: '5.8 MB' },
    { date: '2024-06-15 09:30', name: 'Picking Accuracy', format: 'PDF', status: 'Processing', user: 'Y. Yamamoto', size: '—' },
    { date: '2024-06-14 17:45', name: 'Receiving Variance', format: 'PDF', status: 'Failed', user: 'T. Tanaka', size: '—' },
  ];

  scheduledReports = [
    { id: 1, name: 'Daily Inventory Snapshot', schedule: '0 6 * * *', format: 'Excel', nextRun: '2024-06-16 06:00', active: true },
    { id: 2, name: 'Weekly Shipment Summary', schedule: '0 8 * * MON', format: 'PDF', nextRun: '2024-06-17 08:00', active: true },
    { id: 3, name: 'Monthly Inventory Aging', schedule: '0 7 1 * *', format: 'PDF', nextRun: '2024-07-01 07:00', active: true },
    { id: 4, name: 'Daily Operator Productivity', schedule: '0 22 * * *', format: 'Excel', nextRun: '—', active: false },
  ];

  selectReport(r: any): void { this.selectedReportId = r.id; }
  previewReport(): void { console.log('Preview:', this.selectedReportId); }
  generateReport(): void { console.log('Generate:', this.selectedReportId, this.selectedFormat); }
  downloadReport(h: any): void { console.log('Download:', h.name); }
}
