export const environment = {
  production: false,
  apiUrl: '/api/v1',
  defaultLocale: 'en',
  supportedLocales: ['en', 'ja', 'th'],
  jwtTokenKey: 'wms_access_token',
  jwtRefreshKey: 'wms_refresh_token',
  tokenExpiryKey: 'wms_token_expiry',
  appName: 'WMS Lite',
  appNamePrimary: 'WMS',
  appNameAccent: 'Lite',
  appSubtitle: 'Iventory/Opitimization',
  companyName: 'Warehouse Solutions',
  appVersion: '1.0.0-dev',
  dateFormat: 'yyyy-MM-dd',
  dateTimeFormat: 'yyyy-MM-dd HH:mm:ss',
  defaultPageSize: 20,
  maxPageSize: 200,
  toastLife: 4000,
  sessionTimeoutMinutes: 30,
  enableDebugLog: true
};
